/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zone_rong_imaginebreaker_NativeImagineBreaker */

#ifndef _Included_zone_rong_imaginebreaker_NativeImagineBreaker
#define _Included_zone_rong_imaginebreaker_NativeImagineBreaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zone_rong_imaginebreaker_NativeImagineBreaker
 * Method:    openBaseModules
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zone_rong_imaginebreaker_NativeImagineBreaker_openBaseModules
  (JNIEnv *, jclass);

/*
 * Class:     zone_rong_imaginebreaker_NativeImagineBreaker
 * Method:    removeAllReflectionFilters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zone_rong_imaginebreaker_NativeImagineBreaker_removeAllReflectionFilters
  (JNIEnv *, jclass);

/*
 * Class:     zone_rong_imaginebreaker_NativeImagineBreaker
 * Method:    addExportsToAll0
 * Signature: (Ljava/lang/Module;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zone_rong_imaginebreaker_NativeImagineBreaker_addExportsToAll0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     zone_rong_imaginebreaker_NativeImagineBreaker
 * Method:    weakPairMap_computeIfAbsent
 * Signature: (Ljava/lang/Object;Ljava/lang/Module;Ljava/lang/Module;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_zone_rong_imaginebreaker_NativeImagineBreaker_weakPairMap_1computeIfAbsent
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
